module:
  name:
    key: Module Name
    value_type: string
    value_mapping:
      abc: xyx

  type:
    key: Module Type
    value_type: string
    value_mapping:
      abc: xyx
    default_value: xyz

  artifacts:
    key: List Artifact Info
    value_type: array
    artifact:
      type:
        key: Attribute Type
        value_type: string
        value_mapping:
          Heading: Head
          Information: Info
          MO_FUNC_REQ: MO_FUNC_REQ1
        default_value: xyz

      ReqIF.ForeignID:
        key: Identifier
        value_type: number
        value_mapping:
          abc: xyx
      ReqIF.ForeignCreatedBy:
        key: Creator
        value_type: string
      ReqIF.ForeignModifiedBy:
        key: Contributor
        value_type: string
      ReqIF.ForeignCreatedOn:
        key: Created On
        value_type: date
      ReqIF.ForeignModifiedOn:
        key: Modified On
        value_type: date
      ReqIF.Text:
        key: ReqIF.Text
        value_type: html_string
      ReqIF.Name:
        key: Title
        value_type: html_string
      ReqIF.ChapterName:
        key: ReqIF.Text
        value_type: html_string
      ReqIF.Description:
        key: Description
        value_type: html_string

      __rst__:
        heading:
          atifact_type: Title
          value: Title
        information:
          atifact_type: Info
          directives: 
            - name: sw_req
              attributes:
                id: Identifier
                artifact_type: Information
              html_content: ReqIF.Text
        other:
          directives: 
            - name: sw_req
              attributes:
                id: Identifier
                artifact_type: Description
                crq: crq
                createdOn: Created On
              html_content: ReqIF.Text
              directives:
              - name: subdirective1
                attributes:
                  id: Identifier
                  artifact_type: Description
                  crq: crq
              - name: subdirective2
                attributes:
                  id: Identifier
                  artifact_type: Description
                  crq: crq